language: php

php:
  - 5.5

sudo: required

env:
  - NETCOMMONS_VERSION=master DB=mysql

before_script:
  - export NETCOMMONS_BUILD_DIR=`dirname $TRAVIS_BUILD_DIR`/NetCommons3
  - git clone git://github.com/NetCommons3/NetCommons3 $NETCOMMONS_BUILD_DIR
  - cd $NETCOMMONS_BUILD_DIR
  - git checkout $NETCOMMONS_VERSION
  - travis_wait . tools/build/plugins/cakephp/travis/pre.sh
  - . tools/build/plugins/cakephp/travis/environment.sh

script:
  - export PATH=$PATH:./vendors/bin:$NETCOMMONS_BUILD_DIR/vendors/bin
  - cd $NETCOMMONS_BUILD_DIR
  - app/Console/cake test $PLUGIN_NAME All$PLUGIN_NAME --stderr || exit $?

after_script:
  - . tools/build/plugins/cakephp/travis/post.sh
